osx_image: xcode9.2

sudo: required
dist: xenial

language: c

matrix:
  include:
    - os: osx
      env: TRAVIS_NODE_VERSION="9"
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1 TRAVIS_NODE_VERSION="9"
      compiler: clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgnome-keyring-dev
      - icnsutils
      - graphicsmagick
      - rpm
      - bsdtar

cache:
  directories:
  - $HOME/.electron

install:
  - nvm install $TRAVIS_NODE_VERSION
  - nvm use $TRAVIS_NODE_VERSION
  - npm install -g npm
  - npm install --silent

before_script:
  - export TRAVIS=1
  - npm install --silent
  - npm run lint

script:
  - npm run build
  - npm test

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+.*/"
